spring:
  datasource:
    url: jdbc:mysql://192.168.218.2:3306/sevenstars?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: leilema
    driver-class-name: com.mysql.cj.jdbc.Driver

